AdResd/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AdResd.Models;

namespace AdResd.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AdResd/Controllers/ResidenciasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AdResd.Data;
using AdResd.Models;

namespace AdResd.Controllers
{
    public class ResidenciasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ResidenciasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Residencias
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Residencias.Include(r => r.EncargadoPago).Include(r => r.TipoResidencia);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Residencias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var residencia = await _context.Residencias
                .Include(r => r.EncargadoPago)
                .Include(r => r.TipoResidencia)
                .FirstOrDefaultAsync(m => m.IdResidencia == id);
            if (residencia == null)
            {
                return NotFound();
            }

            return View(residencia);
        }

        // GET: Residencias/Create
        public IActionResult Create()
        {
            ViewData["EncargadoPagoId"] = new SelectList(_context.Set<EncargadoPago>(), "IdEncargadoPago", "NombreEncargado");
            ViewData["TipoResidenciaId"] = new SelectList(_context.Set<TipoResidencia>(), "IdTipoResidencia", "NombreTipoResidencia");
            return View();
        }

        // POST: Residencias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdResidencia,TipoResidenciaId,NumeroDeResidencia,CedulaDuenio,NombresDuenio,ApellidoDuenio,TelefonoDuenio,CorreoDuenio,Arrendado,CedulaArrendatario,NombreArrendatario,ApellidoArrendatario,TelefonoArrendatario,EncargadoPagoId")] Residencia residencia)
        {
            if (ModelState.IsValid)
            {
                _context.Add(residencia);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EncargadoPagoId"] = new SelectList(_context.Set<EncargadoPago>(), "IdEncargadoPago", "NombreEncargado", residencia.EncargadoPagoId);
            ViewData["TipoResidenciaId"] = new SelectList(_context.Set<TipoResidencia>(), "IdTipoResidencia", "NombreTipoResidencia", residencia.TipoResidenciaId);
            return View(residencia);
        }

        // GET: Residencias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var residencia = await _context.Residencias.FindAsync(id);
            if (residencia == null)
            {
                return NotFound();
            }
            ViewData["EncargadoPagoId"] = new SelectList(_context.Set<EncargadoPago>(), "IdEncargadoPago", "IdEncargadoPago", residencia.EncargadoPagoId);
            ViewData["TipoResidenciaId"] = new SelectList(_context.Set<TipoResidencia>(), "IdTipoResidencia", "IdTipoResidencia", residencia.TipoResidenciaId);
            return View(residencia);
        }

        // POST: Residencias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdResidencia,TipoResidenciaId,NumeroDeResidencia,CedulaDuenio,NombresDuenio,ApellidoDuenio,TelefonoDuenio,CorreoDuenio,Arrendado,CedulaArrendatario,NombreArrendatario,ApellidoArrendatario,TelefonoArrendatario,EncargadoPagoId")] Residencia residencia)
        {
            if (id != residencia.IdResidencia)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(residencia);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ResidenciaExists(residencia.IdResidencia))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EncargadoPagoId"] = new SelectList(_context.Set<EncargadoPago>(), "IdEncargadoPago", "IdEncargadoPago", residencia.EncargadoPagoId);
            ViewData["TipoResidenciaId"] = new SelectList(_context.Set<TipoResidencia>(), "IdTipoResidencia", "IdTipoResidencia", residencia.TipoResidenciaId);
            return View(residencia);
        }

        // GET: Residencias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var residencia = await _context.Residencias
                .Include(r => r.EncargadoPago)
                .Include(r => r.TipoResidencia)
                .FirstOrDefaultAsync(m => m.IdResidencia == id);
            if (residencia == null)
            {
                return NotFound();
            }

            return View(residencia);
        }

        // POST: Residencias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var residencia = await _context.Residencias.FindAsync(id);
            _context.Residencias.Remove(residencia);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ResidenciaExists(int id)
        {
            return _context.Residencias.Any(e => e.IdResidencia == id);
        }
    }
}

AdResd/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    @if (User.IsInRole("Administrador"))
    {
        <div class="page-header ">
            <h1 class="h1 padding-2x text-strong text-dark"><small>Panel de Administración</small></h1>
            <hr />
        </div>
        <div class="col-md-12"></div>
            <div class="container mt-5">
                <div class="row">
                    <div class="col-md-3">
                        <a asp-controller="Residencias" asp-action="Index" class="card text-center">
                            <div class="card-header bg-info text-white">
                                <svg width="5em" height="5em" viewBox="0 0 16 16" class="bi bi-house" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M2 13.5V7h1v6.5a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5V7h1v6.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5zm11-11V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z" />
                                    <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z" />
                                </svg>
                            </div>
                            <div class="card-footer">
                                Residencias
                            </div>
                        </a>
                    </div>

                </div>
            </div>

            }

            @if (User.IsInRole("Presidente"))
            {
                <p>gfdf</p>

            }

            @if (User.IsInRole("Tesorero"))
            {
                <p>gfdadsf</p>
            }
            }
            else
            {

            <div class="text-center">
                <h1 class="display-4">Welcome</h1>
                <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
            </div>
            }